title: CV
author: Benod Pradhan
email: 
description: > # this means to ignore newlines until "baseurl:"
  Very Funny 1234
# social links
twitter_username: donibrp
github_username:  dobibrp
linkedin_username: donibrp
facebook_username: donibrp

show_excerpts: to be filled # set to false to remove excerpts on the homepage

theme: minima
